application: techscout-locator # nearwhonearwoo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /icon.png
  static_files: images/techscouts_icon.png
  upload: images/techscouts_icon.png

- url: /
  upload: html/main.html
  static_files: html/main.html

- url: /module.js
  upload: js/module.js
  static_files: js/module.js

- url: /map.js
  upload: js/map_setup.js
  static_files: js/map_setup.js

- url: /pin.js
  upload: js/pin_changes.js
  static_files: js/pin_changes.js

- url: /ion.rangeSlider.min.js
  upload: js/ion.rangeSlider.min.js
  static_files: js/ion.rangeSlider.min.js

- url: /main.css
  upload: css/main.css
  static_files: css/main.css

- url: /ion.rangeSlider.css
  upload: css/ion.rangeSlider.css
  static_files: css/ion.rangeSlider.css

- url: /ion.rangeSlider.skinFlat.css
  upload: css/ion.rangeSlider.skinFlat.css
  static_files: css/ion.rangeSlider.skinFlat.css

- url: /normalize.min.css
  upload: css/normalize.min.css
  static_files: css/normalize.min.css

libraries:
- name: webapp2
  version: "2.5.2"
